name: Verification

on:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    name: Build and test the ui App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Angular CLI
        run: npm install -g @angular/cli
      
      - name: Install dependencies
        run: npm install

      - name: Build app
        run: ng build

      - name: Test app
        run: ng test --browsers=ChromeHeadless --watch=false

